# Generated by Django 3.2.2 on 2021-06-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interface_type_table',
            options={'verbose_name_plural': 'Interface Type'},
        ),
        migrations.AlterModelOptions(
            name='network_type_table',
            options={'verbose_name_plural': 'Device Type'},
        ),
        migrations.AlterModelOptions(
            name='protocal_table',
            options={'verbose_name_plural': 'Protocal'},
        ),
        migrations.AlterModelOptions(
            name='room_table',
            options={'verbose_name_plural': 'Room'},
        ),
        migrations.RemoveField(
            model_name='interface_table',
            name='interface_number',
        ),
    ]
