# Generated by Django 3.2.2 on 2021-06-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210605_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_routing_table',
            options={'verbose_name_plural': 'Group DHCP'},
        ),
    ]
