# Generated by Django 3.2.2 on 2021-06-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_group_routing_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_acl_table',
            options={'ordering': ('id',), 'verbose_name': 'Group Access Control List', 'verbose_name_plural': 'Group Access Control List'},
        ),
        migrations.AlterModelOptions(
            name='group_dhcp_table',
            options={'ordering': ('id',), 'verbose_name': 'Group DHCP', 'verbose_name_plural': 'Group DHCP'},
        ),
        migrations.AlterModelOptions(
            name='group_interface_table',
            options={'ordering': ('id',), 'verbose_name': 'Group Interface', 'verbose_name_plural': 'Group Interface'},
        ),
        migrations.AlterModelOptions(
            name='group_intertrunk_table',
            options={'ordering': ('id',), 'verbose_name': 'Group Sub-interface Trunk', 'verbose_name_plural': 'Group Sub-interface Trunk'},
        ),
        migrations.AlterModelOptions(
            name='group_portchannel_table',
            options={'ordering': ('id',), 'verbose_name': 'Group Port Channel', 'verbose_name_plural': 'Group Port Channel'},
        ),
        migrations.AlterModelOptions(
            name='group_routing_table',
            options={'ordering': ('id',), 'verbose_name': 'Group Routing', 'verbose_name_plural': 'Group Routing'},
        ),
        migrations.AlterModelOptions(
            name='group_switchport_table',
            options={'ordering': ('id',), 'verbose_name': 'Group Switch Port', 'verbose_name_plural': 'Group Switch Port'},
        ),
        migrations.AlterModelOptions(
            name='group_vlan_table',
            options={'ordering': ('id',), 'verbose_name': 'Group VLAN', 'verbose_name_plural': 'Group VLAN'},
        ),
        migrations.AlterModelOptions(
            name='interface_table',
            options={'ordering': ('id',), 'verbose_name': 'Interface Device', 'verbose_name_plural': 'Interface Device'},
        ),
        migrations.AlterModelOptions(
            name='interface_type_table',
            options={'ordering': ('id',), 'verbose_name': 'Interface Type', 'verbose_name_plural': 'Interface Type'},
        ),
        migrations.AlterModelOptions(
            name='network_type_table',
            options={'ordering': ('id',), 'verbose_name': 'Device Type', 'verbose_name_plural': 'Device Type'},
        ),
        migrations.AlterModelOptions(
            name='protocal_table',
            options={'ordering': ('id',), 'verbose_name': 'Protocal', 'verbose_name_plural': 'Protocal'},
        ),
        migrations.AlterModelOptions(
            name='room_table',
            options={'ordering': ('id',), 'verbose_name': 'Room', 'verbose_name_plural': 'Room'},
        ),
        migrations.AlterModelOptions(
            name='switchport_mode_table',
            options={'ordering': ('id',), 'verbose_name': 'Switch Port Mode', 'verbose_name_plural': 'Switch Port Mode'},
        ),
        migrations.AlterModelOptions(
            name='vlan_table',
            options={'ordering': ('id',), 'verbose_name': 'VLAN', 'verbose_name_plural': 'VLAN'},
        ),
        migrations.AlterField(
            model_name='interface_table',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interface_table',
            name='interface',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interface_table',
            name='ip_netmask',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
