# Generated by Django 3.2.2 on 2021-06-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210607_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl_policy_table',
            name='acl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl_policy', to='network.acl_table'),
        ),
        migrations.AlterField(
            model_name='acl_policy_table',
            name='protocal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl_policy', to='network.protocal_table'),
        ),
        migrations.AlterField(
            model_name='acl_table',
            name='group_acl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='network.group_acl_table'),
        ),
        migrations.AlterField(
            model_name='acl_table',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='network.interface_table'),
        ),
        migrations.AlterField(
            model_name='dhcp_table',
            name='group_dhcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dhcp', to='network.group_dhcp_table'),
        ),
        migrations.AlterField(
            model_name='dhcp_table',
            name='interface_helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dhcp', to='network.interface_table'),
        ),
        migrations.AlterField(
            model_name='eigrp_network_table',
            name='eigrp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eigrp_network', to='network.eigrp_table'),
        ),
        migrations.AlterField(
            model_name='eigrp_network_table',
            name='passive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eigrp_network', to='network.group_interface_table'),
        ),
        migrations.AlterField(
            model_name='eigrp_table',
            name='group_routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eigrp', to='network.group_routing_table'),
        ),
        migrations.AlterField(
            model_name='hsrp_table',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hsrp', to='network.interface_table'),
        ),
        migrations.AlterField(
            model_name='interface_table',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interface_table',
            name='group_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface', to='network.group_interface_table'),
        ),
        migrations.AlterField(
            model_name='interface_table',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface', to='network.network_table'),
        ),
        migrations.AlterField(
            model_name='intertrunk_table',
            name='group_intertrunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intertrunk', to='network.group_intertrunk_table'),
        ),
        migrations.AlterField(
            model_name='intertrunk_table',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intertrunk', to='network.interface_table'),
        ),
        migrations.AlterField(
            model_name='intertrunk_table',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intertrunk', to='network.vlan_table'),
        ),
        migrations.AlterField(
            model_name='iot_table',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iot', to='network.network_table'),
        ),
        migrations.AlterField(
            model_name='iot_table',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iot', to='network.profile_table'),
        ),
        migrations.AlterField(
            model_name='iot_table',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iot', to='network.room_table'),
        ),
        migrations.AlterField(
            model_name='nat_pat_table',
            name='acl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nat_pat', to='network.acl_table'),
        ),
        migrations.AlterField(
            model_name='nat_pat_table',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nat_pat', to='network.interface_table'),
        ),
        migrations.AlterField(
            model_name='nat_pat_table',
            name='nat_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nat_pat', to='network.nat_pool_table'),
        ),
        migrations.AlterField(
            model_name='network_table',
            name='interface_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network', to='network.interface_type_table'),
        ),
        migrations.AlterField(
            model_name='network_table',
            name='network_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network', to='network.network_type_table'),
        ),
        migrations.AlterField(
            model_name='portchannel_table',
            name='group_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portchannel', to='network.group_interface_table'),
        ),
        migrations.AlterField(
            model_name='portchannel_table',
            name='group_portchannel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portchannel', to='network.group_portchannel_table'),
        ),
        migrations.AlterField(
            model_name='portchannel_table',
            name='group_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portchannel', to='network.group_vlan_table'),
        ),
        migrations.AlterField(
            model_name='portchannel_table',
            name='switchport_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portchannel', to='network.switchport_mode_table'),
        ),
        migrations.AlterField(
            model_name='portchannel_table',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portchannel', to='network.vlan_table'),
        ),
        migrations.AlterField(
            model_name='profile_table',
            name='group_acl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='network.group_acl_table'),
        ),
        migrations.AlterField(
            model_name='profile_table',
            name='group_dhcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='network.group_dhcp_table'),
        ),
        migrations.AlterField(
            model_name='profile_table',
            name='group_intertrunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='network.group_intertrunk_table'),
        ),
        migrations.AlterField(
            model_name='profile_table',
            name='group_portchannel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='network.group_portchannel_table'),
        ),
        migrations.AlterField(
            model_name='profile_table',
            name='group_routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='network.group_routing_table'),
        ),
        migrations.AlterField(
            model_name='profile_table',
            name='group_switchport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='network.group_switchport_table'),
        ),
        migrations.AlterField(
            model_name='profile_table',
            name='group_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='network.group_vlan_table'),
        ),
        migrations.AlterField(
            model_name='profile_table',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='network.username_table'),
        ),
        migrations.AlterField(
            model_name='static_route_table',
            name='group_routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_route', to='network.group_routing_table'),
        ),
        migrations.AlterField(
            model_name='switchport_table',
            name='group_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_port', to='network.group_interface_table'),
        ),
        migrations.AlterField(
            model_name='switchport_table',
            name='group_switchport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_port', to='network.group_switchport_table'),
        ),
        migrations.AlterField(
            model_name='switchport_table',
            name='group_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_port', to='network.group_vlan_table'),
        ),
        migrations.AlterField(
            model_name='switchport_table',
            name='switchport_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_port', to='network.switchport_mode_table'),
        ),
        migrations.AlterField(
            model_name='switchport_table',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_port', to='network.vlan_table'),
        ),
        migrations.AlterField(
            model_name='tudo_table',
            name='iot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tudo', to='network.iot_table'),
        ),
        migrations.AlterField(
            model_name='vlan_table',
            name='group_vlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vlan', to='network.group_vlan_table'),
        ),
    ]
