# Generated by Django 3.2.2 on 2021-06-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210610_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intertrunk_table',
            options={'ordering': ('id',), 'verbose_name': 'Sub-Interface', 'verbose_name_plural': 'Sub-Interface'},
        ),
        migrations.AlterField(
            model_name='group_dhcp_table',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
