# Generated by Django 3.2.2 on 2021-06-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210611_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp_table',
            name='helper_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
