# Generated by Django 3.2.2 on 2021-06-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_dhcp_table_helper_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcp_table',
            name='dns_server',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
