# Generated by Django 3.2.2 on 2021-06-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_dhcp_table_dns_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhcp_table',
            options={'ordering': ('id',), 'verbose_name': 'Configuration DHCP', 'verbose_name_plural': 'Configuration DHCP'},
        ),
        migrations.AlterModelOptions(
            name='eigrp_table',
            options={'ordering': ('id',), 'verbose_name': 'EIGRP Routing', 'verbose_name_plural': 'Routing EIGRP'},
        ),
        migrations.AlterModelOptions(
            name='profile_table',
            options={'ordering': ('id',), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterField(
            model_name='tudo_table',
            name='start',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
