# Generated by Django 3.2.2 on 2021-06-28 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210628_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='username_table',
            options={'ordering': ('id',), 'verbose_name': 'Username Password', 'verbose_name_plural': 'Username Password'},
        ),
        migrations.RemoveField(
            model_name='profile_table',
            name='key',
        ),
    ]
