# Generated by Django 3.2.2 on 2021-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210628_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='tudo_table',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
