# Generated by Django 3.2.2 on 2021-06-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20210629_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tudo_table',
            name='check',
            field=models.BooleanField(default=True),
        ),
    ]
