# Generated by Django 3.2.2 on 2021-06-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20210629_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tudo_table',
            name='flow',
        ),
    ]
