# Generated by Django 3.2.2 on 2021-06-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20210630_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='topology_table',
        ),
    ]
