# Generated by Django 3.2.2 on 2021-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_topology_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topology_table',
            name='interface',
        ),
        migrations.AddField(
            model_name='topology_table',
            name='interface',
            field=models.ManyToManyField(blank=True, to='network.interface_table'),
        ),
        migrations.RemoveField(
            model_name='topology_table',
            name='vlan',
        ),
        migrations.AddField(
            model_name='topology_table',
            name='vlan',
            field=models.ManyToManyField(blank=True, to='network.vlan_table'),
        ),
    ]
