# Generated by Django 3.2.2 on 2021-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_traffic_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic_table',
            name='interface_out_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='traffic_table',
            name='interface_out_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
