# Generated by Django 3.2.2 on 2021-07-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_auto_20210701_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic_table',
            name='interface_out_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='traffic_table',
            name='interface_out_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
