# Generated by Django 3.2.2 on 2021-07-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_auto_20210701_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='traffic_table',
        ),
    ]
