# Generated by Django 3.2.2 on 2021-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_traffic_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic_table',
            name='interface_out_1',
        ),
        migrations.RemoveField(
            model_name='traffic_table',
            name='interface_out_2',
        ),
        migrations.AddField(
            model_name='traffic_table',
            name='interface',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traffic_table',
            name='packets',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
