# Generated by Django 3.2.2 on 2021-07-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_auto_20210701_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tudo_table',
            name='command',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
