# Generated by Django 3.2.2 on 2021-07-08 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_alter_tudo_table_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topology_table',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='topology_table',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topology_table',
            name='vlan',
        ),
        migrations.DeleteModel(
            name='traffic_table',
        ),
        migrations.AlterModelOptions(
            name='network_table',
            options={'ordering': ('id',), 'verbose_name': 'Network Device', 'verbose_name_plural': 'Network Device'},
        ),
        migrations.RemoveField(
            model_name='interface_table',
            name='group_interface',
        ),
        migrations.AddField(
            model_name='interface_table',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface', to='network.vlan_table'),
        ),
        migrations.DeleteModel(
            name='topology_table',
        ),
    ]
