# Generated by Django 3.2.2 on 2021-07-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_auto_20210708_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_table',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
