# Generated by Django 3.2.2 on 2021-07-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_alter_interface_table_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_table',
            name='lb',
            field=models.BooleanField(default=False),
        ),
    ]
