# Generated by Django 3.2.2 on 2021-07-09 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_iot_table_lb'),
    ]

    operations = [
        migrations.CreateModel(
            name='traffic_interface_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RXBS', models.CharField(blank=True, max_length=50, null=True)),
                ('TXBS', models.CharField(blank=True, max_length=50, null=True)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_interface', to='network.interface_table')),
            ],
            options={
                'verbose_name': 'Traffic Interface',
                'verbose_name_plural': 'Traffic Interface',
                'ordering': ('id',),
            },
        ),
    ]
