# Generated by Django 3.2.2 on 2021-07-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_traffic_interface_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_table',
            name='subscribe',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
