# Generated by Django 3.2.2 on 2021-07-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_iot_table_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='traffic_interface_table',
        ),
    ]
