# Generated by Django 3.2.2 on 2021-07-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_traffic_interface_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='load_balance_stp_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_interface', to='network.network_table')),
            ],
            options={
                'verbose_name': 'STP LB',
                'verbose_name_plural': 'STP LB',
                'ordering': ('id',),
            },
        ),
    ]
