# Generated by Django 3.2.2 on 2021-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0037_load_balance_stp_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_balance_stp_table',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='load_balance_stp_table',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
