# Generated by Django 3.2.2 on 2021-07-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0038_auto_20210712_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iot_table',
            old_name='lb',
            new_name='lb_max',
        ),
        migrations.AddField(
            model_name='iot_table',
            name='lb_avg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iot_table',
            name='lb_min',
            field=models.BooleanField(default=False),
        ),
    ]
