# Generated by Django 3.2.2 on 2021-08-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0043_count_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_table',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count', to='network.network_table'),
        ),
    ]
